### ISSUE TITLE
Class Rakshazi\\string does not exist

### ISSUE THREAD

**Issue by angelxmoreno** [rakshazi/getSetTrait#1]
https://github.com/rakshazi/getSetTrait/blob/5a5cd0e7aeaa022c7b2d771be9c09e0c4d08a5e8/src/GetSetTrait.php#L101

`string` is not a valid type for type hinting until PHP 7

**Comment by angelxmoreno** [comment]
i can open a PR to remove this and keep the lib 5.4+ compatible is the author wishes.

**Comment by rakshazi** [comment]
Hi @angelxmoreno 
Thank you for this issue!
Yes, it will be perfect if you create PR with fix

**Comment by angelxmoreno** [comment]
PR is open.
